language: cpp
sudo: false
dist: trusty
ruby: 2.2.0
cache: bundler
addons:
  apt:
    packages:
      - clang-format-3.5
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++
      env:
        - CXX_COMPILER='g++'
        - RUN_DANGER=false
    - os: linux
      addons:
        apt:
          packages:
            - clang
            - clang-format-3.5
      env:
        - CXX_COMPILER='clang++'
        - RUN_DANGER=true
before_script:
- cmake --version
- |
  if [[ "${RUN_DANGER}" = true ]]; then
    bundle install
  fi
script:
- |
  if [[ "${RUN_DANGER}" = true ]]; then
    bundle exec danger 
  fi
- cmake -H. -Bbuild
- cd build
- cmake --build .
- ctest
